import type { KeyboardBind } from './bindingTypes';

function Say(str: string, times: number) {
  console.log(str.repeat(times));
}

function SayStuff() {
  console.log('Stuff!');
}

const keyboardBindings: {[input: string]: KeyboardBind}[] = [
    {
        a: 'gripRotOpen',
        b: '',
        c: '',
        d: '',
        e: '',
        f: '',
        g: '',
        h: '',
        i: '',
        j: '',
        k: '',
        l: '',
        m: '',
        n: '',
        o: '',
        p: '',
        q: '',
        r: '',
        s: '',
        t: '',
        u: '',
        v: '',
        w: '',
        x: '',
        y: '',
        z: '',
        '0': SayStuff,
        '1': SayStuff,
        '2': { function: SayStuff },
        '3': { function: Say, args: ['Hello', 3] },
        '4': '',
        '5': '',
        '6': '',
        '7': '',
        '8': '',
        '9': '',
        Enter: '',
        Escape: '',
        Backspace: '',
        Tab: '',
        Shift: '',
        Control: '',
        Alt: '',
        CapsLock: '',
        ArrowUp: '',
        ArrowDown: '',
        ArrowLeft: 'move_left_drivebase_side_message',
        ArrowRight: 'move_right_drivebase_side_message',
        ' ': '',
    },
    {
        a: '',
        b: '',
        c: '',
        d: '',
        e: '',
        f: '',
        g: '',
        h: '',
        i: '',
        j: '',
        k: '',
        l: '',
        m: '',
        n: '',
        o: '',
        p: '',
        q: '',
        r: '',
        s: '',
        t: '',
        u: '',
        v: '',
        w: '',
        x: '',
        y: '',
        z: '',
        '0': '',
        '1': '',
        '2': '',
        '3': '',
        '4': '',
        '5': '',
        '6': '',
        '7': '',
        '8': '',
        '9': '',
        Enter: '',
        Escape: '',
        Backspace: '',
        Tab: '',
        Shift: '',
        Control: '',
        Alt: '',
        CapsLock: '',
        ArrowUp: '',
        ArrowDown: '',
        ArrowLeft: '',
        ArrowRight: '',
        ' ': '',
    }
]

export default keyboardBindings;